### ISSUE TITLE
Automatic Movement Causes Motion Sickness

### ISSUE THREAD

**Issue by DarkAthena** [manuelpoell/sit#1]
I love your extension for Owlbear Rodeo! 

One of my players has mentioned that the automatic movement during rounds makes him motion sick. Is there a way to disable it or alter the extension to make movement optional? 

Thank you :)

**Comment by manuelpoell** [comment]
Hi, I'm really glad you like it and thanks for your feedback! :)
I will definitely take a look at it, as I want to make my extension enjoyable for everybody.

I just have to figure out what would be the best possible way on how to configure such things in the UI. Open for any kind of suggestions :)

**Comment by manuelpoell** [comment]
I just released SIT version 1.2.0, which added a config panel for the GM only. Here you can disable the active token autofocus for all players in the current room.
The config panel is likely to be extended in the future with more features.

Have fun playing! :)
