### ISSUE TITLE
Idea: Token names

### ISSUE THREAD

**Issue by Gata-chan** [manuelpoell/sit#3]
I am really loving the tool and the thing about tracking rounds and focusing is great, but I feel like I am hindered by one thing:

**_THE TOKEN NAMES_**

Specifically where the names in the initiative tracker are sourced from - the hard-lined token names, the one that persists between scenes and it doesn't seem to change when you edit the text underneath it, which makes it a little annoying inconvinient because I usually run into a situation where a token looks the same and the original OB tracker uses the attached text underneath if you change it and not the token name (which would make them look absolutely the same and difficult to distinguish in the turn order)

I know it's a small thing but it'd be cool if there was a feature of being able to change the name in the turn order or the name for the order is pulled from the attached text, thank you

An example of such issue: 
![image](https://github.com/manuelpoell/sit/assets/84407182/9a09e769-0ed1-495a-8180-3b3a192f11e8)

**Comment by manuelpoell** [comment]
Hi, thanks for your feedback, glad you like it! Sadly, I couldn't figure out how to access the custom labels you can attach to the tokens.
I just released SIT version 1.2.1 in which you can change the display name of the characters by clicking on them in the initiative tracker list. I think it is a little more versatile like this and I hope it is sufficient for your needs!
Have fun playing!

**Comment by Gata-chan** [comment]
Thank you, this is exactly what I wanted!
