### ISSUE TITLE
Problem with the token focus function

### ISSUE THREAD

**Issue by Klevy42** [manuelpoell/sit#5]
It seems to me that the function of focusing on the active token does not work as it should.
For example (images) when Gog's turn comes, the screen focuses on Kersten.
I tried to fix it on my own by renaming and changing tokens, but it didn't work out.
![изображение](https://github.com/manuelpoell/sit/assets/141227070/3c26e907-0c5e-4ecb-a7aa-967170d990bf)
![изображение](https://github.com/manuelpoell/sit/assets/141227070/9f17c9d3-a2a6-475f-a84f-f4187802ccf7)

**Comment by manuelpoell** [comment]
Hi, thank you for reporting this issue!

This bug is fixed with SIT version 1.2.2 released just now. Have fun playing!
