### ISSUE TITLE
Character based effects

### ISSUE THREAD

**Issue by rsarres** [manuelpoell/sit#6]
Enhancement suggestion

I think that effects should be character based. For example, if I add a Stun effect to a character token, it should appear on the character line.
The way it is now, effects are hidden on a different text window and are not linked to any character.
Example:
From:
Mage  56
Soldier 34

To:
Character  Init  Effect  Effect duration
Mage        56   Stun    3
Soldier      34   Down  2

**Comment by manuelpoell** [comment]
Hi, thank you very much for your suggestion!

Unfortunately I have to reject this idea. Depending on play and game style, effects can also be targeted to structures or areas, which are not included in the initiative list.

Additionally I would like to keep the extension as clean and minimalistic as possible. Adding more custom texts to the initiative tracker would eventually result in confusing design of the list.

Anyways I'm really glad for your feeback and hope you enjoy playing! Greetings!
