### ISSUE TITLE
Question about focusing on token.

### ISSUE THREAD

**Issue by Klevy42** [manuelpoell/sit#7]
The focus on the marker works only on me - the creator of the room. Players do not see movements, regardless of whether the function is enabled or not. Is that the intention?

**Comment by manuelpoell** [comment]
Hi, thanks for reporting this issue!
It is intended to work for everybody in the room, and sadly it did only work for the player clicking on the next round button.

This behaviour is fixed now and live with SIT version 1.2.3

Thanks and have fun playing!
