### ISSUE TITLE
Hide from player view if token is hidden

### ISSUE THREAD

**Issue by jaquer** [manuelpoell/sit#8]
Hello,

Would it be possible to have the creature be hidden on the players view if the token is marked as hidden? The official tracker does this, but it's missing the amazing condition tracking/token focus that your version has.

GM view:

![](https://github.com/manuelpoell/sit/assets/118391/22450e60-8b37-478a-ac98-30a4283cbb53)

Player view:

![](https://github.com/manuelpoell/sit/assets/118391/7528775a-0027-4ac9-9e44-f18874ccda22)

Either way, thank you for your hard work and for offering this extension.

**Comment by manuelpoell** [comment]
Hi, thanks for your feedback! Love your suggestion, but I don't think it would be a good idea to have separate initiative lists as GM and player, as it would lead to invisible highlighting of the current token for the players. That could make the players feel like the tracker is broken and leads to bad user experience.

Currently the handling for invisible tokens is that the camera is not auto-focusing them, if it's their turn.

I would suggest another solution for the problem: Invisible tokens are not removed from players initiative list, but their names are hidden or replaced with a placeholder like for example "Hidden".  You could toggle this behaviour in the GM menu of the extension.

Let me know what you think of that, and have fun playing! :)
